project:
  title: "Quarto preprint"
  type: website
  render:
    - manual.qmd
  resources:
    - manual-jou.pdf

website:
  repo-url: https://github.com/mvuorre/quarto-preprint
  repo-actions: [edit, source, issue]
