project:
  title: "Quarto preprint"
  type: website
  render:
    - index.qmd
    - example.qmd
  resources:
    - index.html
    - example.pdf
    - example-jou.pdf
  output-dir: docs

website:
  repo-url: https://github.com/mvuorre/quarto-preprint
  repo-actions: [edit, source, issue]
