project:
  title: "Quarto preprint"
  render: 
    - index.qmd
  output-dir: docs

format:
  html:
    toc: true
    fontsize: 12pt
    mainfont: Fira Sans
    other-links: 
      - text: Website
        href: https://mvuorre.github.io/quarto-preprint
        icon: globe2
      - text: GitHub Repository
        href: https://github.com/mvuorre/quarto-preprint
        icon: github
  preprint-typst:
    fontsize: 10pt
    mainfont: Libertinus Serif
  preprint-docx:
    default
